/*
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: Huawei Inc.
 */

package org.eclipse.xpanse.tofu.maker.models.response;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import java.util.Map;
import java.util.UUID;
import lombok.Builder;
import lombok.Data;

/**
 * Data model for the OpenTofu command execution results.
 */
@Data
@Builder
public class OpenTofuResult {

    @Schema(description = "Id of the request.")
    private UUID requestId;
    @NotNull
    @Schema(description = "defines if the command was successfully executed")
    private boolean isCommandSuccessful;
    @Schema(description = "stdout of the command returned as string.")
    private String commandStdOutput;
    @Schema(description = "stderr of the command returned as string.")
    private String commandStdError;
    @Schema(description = ".tfstate file contents returned as string.")
    private String terraformState;
    @Schema(description = "Data of all other files generated by the openTofu execution."
            + "The map key contains the file name and value is the file contents as string.")
    private Map<String, String> importantFileContentMap;
    @Schema(description = "The version of the OpenTofu binary used to execute scripts.")
    String openTofuVersionUsed;
}
